GoogleCloudPlatform/fluent-plugin-google-cloud

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Optional tags (timeNanos and severity) are now consumed when processed.
If we are left with a single tag called 'message' left, we continue to use
textPayload, otherwise we send the record as structPayload.

Add structured logging support.

---

lib/fluent/plugin/out_google_cloud.rb

I verified that this works as expected on GCE. I didn't explicitly check on EC2, but Socket.gethostname should work everywhere, including on Windows.
We could also get this from the metadata service, but then some extra string parsing is needed to pull off some of the extra info and it didn't look like EC2's metadata doc included hostname.
Let me know if this shouldn't be using one of the domain-scoped labels, I don't know what the standards are for them. I'd be happy to change the label key to be hostname.
@mr-salty @goltermann

Include the VM hostname as an additional label when running on GCE or EC2

---

lib/fluent/plugin/out_google_cloud.rb

Fix label map check that prevents labels from being populated properly

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Assumes the usage of [fluent-plugin-kubernetes_metadata_filter](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter), as well as an upcoming change of mine to that plugin to include namespace IDs. The exact field names we parse out of the record may have to change slightly as a result of that, but everything else should be stable.
There are a few issues worth discussing/clarifying/pointing out:
1. Do we want both the container.googleapis.com labels and the compute.googleapis.com labels?
2. Do all the labels belong under container.googleapis.com even though they won't be first-class fields in the log viewer? I assume yes, but my knowledge is out of date.
3. Namespace ID is going to be pretty awkward to add to the metadata filter plugin.
4. We could fall back to parsing …

Add support for better labels on Kubernetes and Container Engine logs.

---

lib/fluent/plugin/out_google_cloud.rb

Just the minor cleanup discussed in #30

Clean up the way that different parts of the code add labels.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Treat them exactly the same as json logs from other sources if they are
json.
Avoid trying to parse every entry as json. If the first entry in a batch
isn't json, then don't try to parse the rest as json, since it's just a
waste of CPU. JSON parsing is unfortunately not cheap. We might consider
switching over to a faster parser (like https://github.com/ohler55/oj).
@mr-salty

Parse container logs into a structured log if their body is json.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

If the project_id has not been set in the config file and cannot be
obtained via the metadata service, try to get it from the credentials.
Add a test for this, and change to using constants for the paths to the
credentials files.

Obtain the project_id from credentials if needed.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

When structPayload contains a httpRequest object with valid fields [1],
extract these values into a new root httpRequest object so Google Cloud
Logging would pick them up as HTTP request attributes.
Hopefully, this would show up in Log Viewer similar to how HTTP requests
are logged for App Engine projects.
[1] https://cloud.google.com/logging/docs/api/ref/rest/v1beta3/projects.logs.entries/write#HttpRequest

Extract httpRequest object from structPayload

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

I have a few refactoring changes to the cloud-logging plugin, preliminary to updating to use googleauth > 0.9.

Minor refactorings of the cloud logging plugin.

---

lib/fluent/plugin/out_google_cloud.rb

* Added the ability to set subservice name, if autodetection of
subservice is disabled.
* Added the ability to configure static labels.

Moved Google Dataflow to be externally configured

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

@a-robinson @mr-salty @bokowski FYI.

Move JSON detection back under the container guard.

---

README.rdoc
fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb

Renaming some APIs to Stackdriver brand

Stackdriver product rename

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb

* b/32474926 gRPC plugin needs to handle invalid UTF-8 chracters

Fix UTF-8 encoding issue with gRPC support

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Igor, do you have any opinion on using singular nouns for this counter, when we use plural for the others? Singular is in line with Stackdriver best practices.

Added stackdriver_retried_entries_count counter

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

 Refactor gRPC path to use LoggingServiceV2Client.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Revert #179, because it breaks authentication.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb

This is a prerequisite of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/202.

Refactor writing requests as prerequisite of tag grouping revamp.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud_grpc.rb

This PR depends on https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/192.

Add partial success for gRPC path.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Allow overriding k8s_cluster_name and k8s_cluster_location in the config.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Also add unit tests for User-Agent on both paths.

Set User-Agent on the gRPC path.

---

test/plugin/base_test.rb
test/plugin/constants.rb

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/229 depends on this.

Add container tag when testing k8s container resource.

---

test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Follow up of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/273.

Add more unit tests for LogEntry fields.

---

.rubocop.yml
.travis.yml

Also update rubocop to Ruby 2.3+.

Add Ruby 2.5 to Travis Build config and remove Ruby 2.2.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud_grpc.rb

Also bump the fluentd dependency version to 1.4.2.

Bump googleauth to 0.8.1.

---

README.rdoc

Fix broken links to the Fluentd docs.

---

lib/fluent/plugin/monitoring.rb
test/plugin/base_test.rb

The previous version was using the same metric labels as the raw metrics in Prometheus. However, we need to write to the schema of the curated metrics. This change introduces the expected translation. This is only intended for legacy metrics; in the future we should make the raw metric equal to the curated metric.
I tested this from a GCE VM and it's working (on a not very lively VM):

Fixed schema of OpenCensus metrics.

---

fluent-plugin-google-cloud.gemspec

Verified that everything looks good.
CPU: 
RSS:
Throughput:

Update Fluentd to 1.7.4.

---

fluent-plugin-google-cloud.gemspec

Revert json gem version from 2.4.1 to 2.2.0 for memory regression.

---

lib/fluent/plugin/out_google_cloud.rb

Added misc. severity translation information/info to enable getting logs from for exp. `ClickHouseDB`

Added misc. severity translation information/info

---

test/plugin/base_test.rb

Tested in: cl/485477857 presubmit tests

Replace URI decode with CGI unescape

---

.github/workflows/ci.yml
.rubocop.yml
.rubocop_todo.yml
Rakefile
fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/common.rb
lib/fluent/plugin/filter_add_insert_ids.rb
lib/fluent/plugin/filter_analyze_config.rb
lib/fluent/plugin/in_object_space_dump.rb
lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb
lib/fluent/plugin/statusz.rb
test/helper.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_driver.rb
test/plugin/test_filter_add_insert_ids.rb
test/plugin/test_filter_analyze_config.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb
test/plugin/utils.rb

Also fix all of the new warnings.
[b/272577695](http://b/272577695).
See also https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/pull/101.

Bump rubocop version to 1.48.1.

---

fluent-plugin-google-cloud.gemspec

[b/290385216](http://b/290385216)
See also https://github.com/GoogleCloudPlatform/google-fluentd/pull/417.

Upgrading grpc to 1.53.0
