lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- Ensure we only send valid severity enum values (or 'DEFAULT' if unknown).
- Translate "known" (mostly log4j) values into valid values.
- Translate single-character severities into valid values.
- Constrain numeric severities to valid values (multiples of 100 from 0-800).

Improve severity level support.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

This pull request is to support setting custom GCE metadata from config.
Why do I need this feature is I want to use fluent-plugin-google-cloud from any servers not only GCE instances.
Google Cloud Logging is very awesome feature, but current fluent-plugin-google-cloud can only work on GCE instance, because plugin get instance metadata (project_id, zone, vm_id) using local API.
I'm very happy that you merge this pull request if you can.

Support setting custom GCE metadata from config

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/data/credentials.json
test/plugin/data/invalid_credentials.json
test/plugin/test_out_google_cloud.rb

* Support Application Default Credentials and JSON keys.
* Application Default Credentials is now the default.
Note that this still falls back to using the service account if no other
credentials are found so there should be no change for existing users.
* auth_method is now deprecated; we emit a warning if it is configured.
private_key is still supported for existing users.
* add a config option application_default_credentials_path, since setting
environment variables for fluentd is inconvenient.
* The default path is $HOME/.config/gcloud/application_default_credentials.json
($HOME likely resolves to /root on GCE)
* Ensure the tests are actually exercising all auth methods (and using
Application Default Credentials for most tests).
* Some misc cleanup in tests.

Add support for Application Default Credentials.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- Fix a bug where we tried to fetch GCE metadata in one case even when
fetch_gce_metadata was false.
- Factor the GCE fake stub setup out of the tests so we can control when they
are installed
- Add a test that sends a log with custom metadata to make sure we're
exercising this code path (I verfied the test fails without the change
to the plugin so it would have caught this bug).

Fix a metadata exception on non-GCE platforms

---

test/plugin/test_out_google_cloud.rb

When I checked out current master branch and run `bundle exec rake test`, I got following error.
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST https://www.googleapis.com/oauth2/v3/token with body 'grant_type=refresh_token&refresh_token=1%2FBrB9HSuFjmdqNUdYqaisimWm0RC2Bbj8AnbWJ4eNw9w&client_id=32555940559.apps.googleusercontent.com&client_secret=ZmssLNjJy2998hD4CTg2ejr2' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Cache-Control'=>'no-store', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Ruby'}
... (Getting same errors ....)
26 tests, 134 assertions, 0 failures, 14 errors, 0 pendings, 0 omissions, 0 notifications
46.1538% passed
```
I add stub request for …

Add stub request for refresh auth token to fix failed test

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Rename the config option fetch_gce_metadata to use_metadata_service
so it applies to non-GCE platforms.

Rename fetch_gce_metadata to use_metadata_service

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- timeNanos is deprecated because the 53 bit mantissa used for doubles
does not have sufficient precision to represent the current time in
nanoseconds past the unix epoch (which currently requires 61 bits).
- instead, we now support formats with split seconds and nanoseconds:
- timestampSeconds, timestampNanos
- timestamp { seconds, nanos }
In both cases, the "seconds" part represents seconds since the unix epoch,
and the "nano" part is the nanosecond component only (0..999999999).
Managed VMs is using the latter, but it can only be ingested via
json/msgpack/etc, while the former is suitable for use in an in_tail regex.
This should be considered an interim solution until
https://github.com/fluent/fluentd/issues/461 is resolved.

Improve nanosecond timestamp support.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- fluentd requires 'record' to be a hash, but since it does not enforce that
there are ways for non-hash records to slip through.  although this will
be fixed upstream, it doesn't hurt to be defensive like some other plugins
do.  without this change we will throw an exception.
See https://github.com/fluent/fluentd/issues/591

Drop log entries which are not Hashes.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

The documentation doesn't give any guidance about whether to use the name
or IP address, but I've had customer reports (on Docker) of failing to
resolve the name, so using the IP address and eliminating the DNS
dependency (the name is *not* in /etc/hosts) seems preferable.
There's precedent for doing this in
https://github.com/google/google-auth-library-ruby

Replace uses of 'metadata' with IP 169.254.169.254

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- Previously, the plugin could either obtain metadata from the metadata
service or from the config file, depending on the setting of
use_metadata_service.
- Now, we allow the user to override metadata in the config file even
if use_metadata_service is true (the default).  Configured data has
precedence over data obtained from the service.
- Fetching from the metadata service now happens in config() rather
than start().  This shouldn't have any practical impact.
- I restructured the tests a bit and added tests for various illegal
configs and overriding data.

Allow overriding metadata service attributes.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- Detect whether we're running on ec2 using the [metadata server](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html)
- Add EC2 service name and label values:
- service = ec2.amazonaws.com
- zone = *availabiltyZone from metadata* (with aws: prefix)
- ec2.amazonaws.com/resource_type = "instance"
- ec2.amazonaws.com/resource_id = *instanceId from metadata*
- ec2.amazonaws.com/account_id = *accountId from metadata*

Add support for EC2 platform and metadata.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

- Add a label_map configuration option
label_map (specified as a JSON object) is an unordered set of fluent 
field names whose values are sent as labels rather than as part of the
struct payload.
Each entry in the map is a {"field_name": "label_name"} pair.  When
the "field_name" (as parsed by the input plugin) is encountered, a label
with the corresponding "label_name" is added to the log entry.  The
value of the field is used as the value of the label.
The map gives the user additional flexibility in specifying label
names, including the ability to use characters which would not be
legal as part of fluent field names.
Example:
```
label_map {
"field_name_1": "sent_label_name_1",
"field_name_2": "some.prefix/sent_label_name_2"
}
```
- Ancillary change: modify the test to use the 'v1' …

Add support for configuring user-defined labels.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Label values are required to be strings, so when using label_map,
coerce the parsed value to be a string.
I confirmed the test I added failed before changing the plugin and
passes now.
Rubocop also made me make a couple changes (including replacing the
conditional with 'next unless ...')

Ensure label values are strings.

---

fluent-plugin-google-cloud.gemspec

Fixed a spelling error s/loge/logs/ and removed the trailing
single quote from the end of the string since it's unnecessary.

Gemspec description update

---

lib/fluent/plugin/out_google_cloud.rb

`private_key_passphrase` contains sensitive information. 
This parameter should be concealed with secret parameter feature.

Add a secret parameter

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

This will be useful in the short term, because the kubernetes metadata
filter plugin isn't actually broadly usable until another kubernetes
feature (the daemon controller) gets in that will allow the metadata
plugin to authenticate to the kubernetes API.
This breaks rubocop due to the long write() function. It probably needs broader refactoring than what belongs in this commit, but I'm happy to fix it up here if you'd like.
@mr-salty @jimmidyson @brendandburns

Add support for attaching container metadata based on the tag.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

the instance metadata.
The plan for Kubernetes is to have 2 out_google_cloud stanzas in our
configuration, one which handles node daemon logs and sets this to true,
and one which handles the container logs and doesn't set this.
@mr-salty @vishh @swalkowski
Cross reference https://github.com/kubernetes/kubernetes/issues/13033

Add option to allow for forcing the service of logs to be GCE, ignoring

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Also make the regexp configurable, since the default won't work for
configurations in which there's more than one component of the tag
before the part we care about.
@mr-salty @swalkowski

Fix the kubernetes tag regexp to allow pod names with periods in them.

---

test/plugin/test_out_google_cloud.rb

This makes the error message label the expectation and actual value
correctly rather than mixing them up.
Just a minor thing I bumped into while verifying #36.
@mr-salty

Fix misordered expectation and value in assert statement.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

This way logs coming from functions are processed in a custom way, by extracting certain labels (function name, execution id) and fields (timestamp, severity) from tag name and log text, and marking the entries with Cloud Functions service name.
@mr-salty @rsokolowski

Add support for Cloud Functions logs

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

This prevents too many different log streams from being created for pods
in a replication controller, and allows for much better aggregation.
It could be confusing if people don't name their containers well, but in our experience most people tend to just name their container the same as the pod that it's in, and don't use meaningless names for them.
If it's alright, I'm going to be shortly following this up by also including whether it's stdout or stderr in the log name as well, making for names like "redis.stdout" and "redis.stderr" coming from a redis container. This'll also make it such that the payload can be just the log message, with no unnecessary json boilerplate. That'll take a little more surgery, though, since each batch of logs for the tag might have to be split into two …

Use the Kubernetes container name as the log name rather than the tag.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

In the process, switch over from using structPayload to textPayload.
Picking this over the alternatives of splitting the logs into two separate streams (containername.stdout and containername.stderr) or by shoehorning this into the severity field. Not choosing separate streams because it makes it tougher to aggregate them and aggregating them seems like the more common case. Not choosing to use the severity field because it doesn't really fit the model as well -- what if we later want to actually parse severity out of container logs, or if docker starts allowing more stream names than just stdout and stderr?
I'm happy to use a different label than container.googleapis.com/stream if you have other suggestions. container.googleapis.com/stream_name, perhaps?
@mr-salty for review
@bokowski …

Make kubernetes logs map the stream into a label rather than the payload

---

lib/fluent/plugin/out_google_cloud.rb

This is currently done by the install script, but it is broken for
non-GCE platforms and is better done here, so it will also work for
people who don't use the install script.

Log a message containing the URL of the log viewer.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/data/iam-credentials.json
test/plugin/test_out_google_cloud.rb

This new credentials format is currently rolling out to all users; the
email address format is account@project-id.iam.gserviceaccount.com.
The existing format is still supported.

Parse project_id from IAM account credentials.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

The condition checked when populating Kubernetes labels to logging labels was incorrect. Relevant test extended to check that it works as expected.
Please wait for @a-robinson LGTM.
@a-robinson @mr-salty

Fix the condition for populating Kubernetes labels

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Adding support for encoded function names extracted from a tag. Updating the Cloud Functions tag regexp to reflect the expected format.
Moving the block which sets current service name when running Cloud Functions before the name is read.
@mr-salty

Support encoded names of cloud functions and set service name properly

---

.travis.yml
fluent-plugin-google-cloud.gemspec

Maintaining support for 1.9 has become a chore, and it's been
offically EOL for over a year.
The upcoming fluentd-0.14 will also drop support for ruby 1.9.

Require Ruby version 2.0 or greater.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

* Fix newly introduced warnings (extra parens, variable case)
* also remove a renundant required_ruby_version that crept in.

Update to rubocop 0.35

---

Rakefile

This will help ensure the file permissions are correct during a gem release.  (see #53)

Check file permissions of the plugin in Rakefile.

---

test/plugin/test_out_google_cloud.rb

This makes them more accurately match the logs that are actually generated by Docker for Kubernetes containers.
@mr-salty @bokowski

Include a timestamp in the test's kubernetes logs.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Current behavior is to use the ingestion time; the 'time' value is not used.

Parse timestamps that k8s puts in a field 'time'

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Set the severity to INFO for log messages coming from stdout,
and to ERROR for stderr.
No new code here, just a rebased version of @bokowski's #70
@igorpeshansky

For k8s/Docker, use the stream to determine severity.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

This takes @bokowski's #65, resolves the merge conflict with the other PRs that have gone in recently, and fixes the broken tests from #65 by removing the time field from the record while checking for json. That's needed because we don't attempt to parse json if the record itself has multiple fields in it. The time is re-added after the json parsing if needed, as implemented by #69.
@igorpeshansky - I believe this is good to go, with just the one line change on top of #65.

Detect JSON by checking each line, in all ingested logs

---

lib/fluent/plugin/out_google_cloud.rb

This enables Cloud Logging to parse NGINX's [`error.log`](https://www.nginx.com/resources/admin-guide/logging-and-monitoring/) files.

Map NGINX error log levels

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

* Migrate to Logging API v2beta1
* MonitoredResource now specifies the service and keys, rather than using labels
* Update all "hardcoded" services to use the new schema
* Add some special-case code for Dataflow and ML which use labels/label_map config
* Update tests; add tests for dataflow and ML

Migrate to Logging API v2beta1

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

In v1 this happened automatically; in v2 we have to do it ourselves,
or the API will reject it.
I should have been more wary when I had to change the test.

Escape the slash used for the appengine log prefix.

---

fluent-plugin-google-cloud.gemspec
test/plugin/test_out_google_cloud.rb

Removed Fluentd version pin. Fixed test which now supports nanosecond timestamp log message verification. Updated function call to remove variable name declaration for use_v1_config (no longer seems to be supported). This is effectively a revert of #73.

Update Fluentd version to latest

---

test/plugin/base_test.rb

Verified that we are not doing any special json parsing when converting malformatted hash key to string in the REST path (Otherwise the key would show up as `['[1,2,3,4]']` instead of `['[1, 2, 3, 4]']`).
Added some test cases.

Add test cases for malformated json key handling.

---

fluent-plugin-google-cloud.gemspec

The latest grpc gem broke one of our tests related to `GRPC::Cancelled`. Seems the default error message ("unknown cause") is returned instead of ("Cancelled"). To unblock us from releasing our gem, we decided to pin the grpc version to `1.0.1` before a fix in grpc is placed.
```
1.1.2 - February 10, 2017 x64-mingw32 (2.85 MB)
1.1.2 - February 10, 2017 x86_64-linux (7.41 MB)
1.1.2 - February 10, 2017 universal-darwin (4.18 MB)
1.1.2 - February 10, 2017 x86-mingw32 (2.85 MB)
1.1.2 - February 10, 2017 (2.3 MB)
1.0.1 - October 27, 2016 universal-darwin (3.16 MB)
1.0.1 - October 27, 2016 x64-mingw32 (2.57 MB)
1.0.1 - October 27, 2016 x86-mingw32 (2.57 MB)
1.0.1 - October 27, 2016 x86_64-linux (6.11 MB)
1.0.1 - October 27, 2016 x86-linux (5.58 MB)
```

Pin gRPC gem version to 1.0.1 until the GRPC::Cancelled bug is fixed.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Backporting the fix to the non-grpc path. This is to address https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/84.

Leave absent fields unset in 'http_request' for non-grpc path.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

When constructing a monitored resource, translate namespace_name and pod_name to namespace_id and pod_id, respectively.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Adding Cloud Dataproc support directly to plugin (currently Cloud Dataproc image uses a forked version of the plugin).

Add Google Cloud Dataproc support.

---

fluent-plugin-google-cloud.gemspec

Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/139 by working around https://github.com/google/google-auth-library-ruby/issues/113.

Pin googleauth gem version at 0.5.1 because of https://github.com/google/google-auth-library-ruby/issues/113.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

This fixes part of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/126. This is just for the `trace` field, but I plan to do a similar change for `operation`.
This makes the `trace_key` default to `logging.googleapis.com/trace` to not conflict with any users who happen to use `"trace"` as a log entry field.
There is also a `keep_trace_key` setting to control whether the trace value is retained in the `jsonPayload` in addition to being set on the LogEntry itself. That's in line with the discussion at https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4.
This upgrades the `google-cloud-logging` gem dependency as the new version was needed to support the `trace` field in the LogEntry proto for gRPC.

Allow setting LogEntry trace field via record

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

Fixes the case when timestamp components are parsed out of logs as strings.

Convert timestamp Strings with Integer values to Integers.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Per suggestion by @qingling128 that we remove this config option (see 
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/145#issuecomment-321007748).
This new config option did not end up getting released to customers, so I think we are safe to remove it now before the next release goes out.

Remove keep_trace_key config option

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

* Remove unnecessary instance variables: `@running_on_managed_vm`,
`@gae_backend_name` and `@gae_backend_version`.
* Refactor the `configure` function to improve readability by separating
different sections into smaller functions.
* Separate the logic to set labels for different monitored resources to improve
readability and maintainability.
* Add comments for confusing logic in the code and explain the story behind them
to improve readability and also serve as a reminder that this might be
something we could revisit.
* Combine tests.

Refactoring and cleaning up.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Dispatch the data to the correct fields for `sourceLocation` and `operation`, like it's done for `httpRequest`
I have also merged the `labels` into the record labels, if no conflict is present
fixes #126

Get source_location, operation and labels from the record if any are available.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

The extraction of `labels` field from the record is kind of a major feature, and should go through product first. Reverting this part of the changes that was originally added in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/145.

Revert support for labels in log entry.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Also adds `'msg'` as a supported text payload key for JSON detection.
@meltsufin FYI. Should allow #89 to be fixed on the AppEngine side.
@crassirostris FYI.

Make JSON detection a config option, rather than GKE-only.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Added severity translation from "[SEVERE](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Level.html#SEVERE)" to "[ERROR](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity)."

Add severity translations for java.util.logging.

---

lib/fluent/plugin/out_google_cloud.rb

Should we log retries as `info` or `warn`?

Add logging for retries.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb

These upgrades are required for the coming partial success support.
Changes in these upgrades that affect us:
- `erb` is no longer bundled in Ruby core as of Ruby 2.2, which is required by these new gems. So we have to require it explicitly instead.
- The types of the following fields have been changed from `integer` to `String`: `cache_fill_bytes`, `response_size` and `request_size` in `HttpRequest`, `line` in `SourceLocation`. So we had to change our tests accordingly. https://github.com/google/google-api-ruby-client/issues/619 is created to double check these changes are intended. It feels weird.

Upgrade google-api-client to 0.14.5 and google-cloud-logging to 1.2.3.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Turned out that we never had Cloud ML and CLoud Dataflow tests.
The constants were added during the Logging API V2 Migration: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/110/commits/6eebbc8cb5ff5c632b6e6e688f8db32e7ac1a0e6.
Yet there are no actual tests.
The root cause for the issue is that we should extract certain labels from `common metadata labels` to `resource labels` at the group level. (Previously we only did it at the entry level).

Fix common label extraction for Cloud ML and Dataflow.

---

fluent-plugin-google-cloud.gemspec
test/plugin/base_test.rb
test/plugin/test_out_google_cloud_grpc.rb

There is an open load balancing bug with `gRPC` at https://github.com/grpc/grpc/issues/12506.
Previously we use the same port for all mocks in our test, which triggers a ton of `Call dropped by load balancing policy` errors.
The short term workaround would be to use a different port for each test run. I've tested this change on a GCP VM. It seems to work fine. All logs are ingested. No errors in the Fluentd log.
The issue is still a bit concerning. Yet at least we can start the developing work for partial success which requires `gRPC` `1.6.6`.

Remove gRPC version pin.

---

lib/fluent/plugin/out_google_cloud.rb

#131 by @mururu and @sayap
Tested by editing installed agent plugin code. Saw correct timestamps start to show up for fluentd log entries in Google Cloud Logging webapp.

solution to #131 truncated timestamps

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Upgrade Rubocop to `0.39.0` to pick the fix for this issue: https://github.com/whitequark/parser/issues/283.
This is needed for some unit tests in partial success. We have test data like:
```
'google.rpc.debuginfo-bin' =>
"\x12\xA7\x03[ORIGINAL ERROR] generic::permission_denied: User not auth" \
"orized. [google.rpc.error_details_ext] { message: \"User not authorize" \
"d.\" details { type_url: \"type.googleapis.com/google.logging.v2.Write" \
"LogEntriesPartialErrors\" value: \"\\n\\034\\010\\000\\022\\030\\010\\" \
"007\\022\\024User not authorized.\\n-\\010\\001\\022)\\010\\003\\022%L" \
"og name contains illegal character :\\n-\\010\\002\\022)\\010\\003\\02" \
"2%Log name contains illegal character :\" } }",
```
Rubocop complains about the `\x` part. And there is no way to disable the …

Update Rubocop version to 0.39.0.

---

fluent-plugin-google-cloud.gemspec
test/plugin/base_test.rb

The latest released `google-cloud-logging` gem requires `googleauth` to be > 0.6.1. Our pin conflicts with that. The original bug that triggered us to pin it < `0.5.2`has been fixed, so it should be fine for us to upgrade.

Remove googleauth version pin.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud.rb

Handle non-string severity values in the incoming JSON.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

This will enable logging agent users to associate log entries with particular trace spans.
This requires an update of `google-api-client` and `google-cloud-logging` to support the new spanId field for the REST and gRPC call paths (See https://github.com/google/google-api-ruby-client/commit/35a23f126cde4723059b57954e90db4cf50ce7e9 and https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/48464a68fcdcc68fdd57a4872be2c02588b789dd).

Add spanId field support, bump google-api-client version to 0.17 and google-cloud-logging version to 1.3.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

For gRPC, the official 'OK' code (https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/StatusCode.cs) is 0. Yet for our case, 'successful_requests_count' simply gets mapped as response_code=200 regardless.

Add grpc and status code info in request and entry count metrics.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

Also fix/expand invalid credentials file tests.

Prefer the project id from the credentials file.

---

lib/fluent/plugin/out_google_cloud.rb

Per https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/errors.rb#L91, `GRPC::Cancelled` is a subclass of `GRPC::BadStatus`, thus already covered in the other case. Removing the redundant part.

Remove redundant GRPC::Cancelled case.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

The plugin already sets the logging scope to be requested for newly
acquired access token. However signet ignores this unless it obtains the
refresh token itself. google-fluentd usually uses a service account to
do so. If someone passes in an already created refresh token using the
GOOGLE_REFRESH_TOKEN environment variable, the access token request will
not request the logging scope. This fixes the latter.
More context about the change in signet (0.8+) can be found in
https://github.com/google/signet/pull/89

Request the logging scope from signet when fetching an access token.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

We are seeing a serious / fast memory leak after that comes with gRPC v1.2.5 -> v1.4.5 upgrade which was introduced by a gRPC requirement in google-cloud-logging >= 1.3.0.
For a short-term mitigation for https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/187, we might want to roll it back.
See internal memory leak investigation doc for more details.

Revert #180 and pin google-cloud-logging to < 1.3 and grpc to < 1.3 for memory leak.

---

lib/fluent/plugin/out_google_cloud.rb

Workaround for https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1893

Add exception handling for unexpected errors from google-cloud-logging.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_driver.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

This depends on https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/201.

Add a flag to control whether to group log tags when sending requests to Stackdriver Logging API.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

This is a revert of #196 , which reverts #180 . 
BTW, there is an issue that I observed after the upgrade of `google-cloud-logging`: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1938. It does not seem to be a blocking thing though. We are not getting that warning in Fluentd logs.

Restore #180 and remove google-cloud-logging and grpc pins.

---

lib/fluent/plugin/out_google_cloud.rb

This should address https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1938.

Fix use of deprecated parameter name.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

We've been doing this for REST for now. Should do it for gRPC as well. This change should have been a part of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/174.
A more accurate solution will be addressed in b/70337435.

Consider partially successful requests successful in the counter.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

This is to align with https://github.com/Stackdriver/metadata-agent/pull/56.
The change here does not affect functionality, just the test stubs.

Remove 'Name' from docker and gke local_resource_id prefixes.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

We need to determine "best practices" on the topic of setting a dynamic metadata_agent_url which is dependent on the environment the logging agent is running in. Having the default set to "http://local-metadata-agent.stackdriver.com:8000" only works well when the metadata agent is discoverable on the same network as the logging agent. 
The decision is to support a new configuration parameter that specifies the environment variable `STACKDRIVER_METADATA_AGENT_URL`, which is evaluated after checking the metadata_agent_url before falling back to default.

Support passing metadata agent url via an environment variable STACKDRIVER_METADATA_AGENT_URL.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

This option controls whether Stackdriver Logging Agent will split logs into separate requests based on the log tag. If true, logs with each distinct tag will be grouped into their own request. By default this is currently enabled. The original intention behind splitting logs with different tags into their own requests is to avoid repeatedly setting the log name for every log entry in the batch send to Stackdriver Logging, compressing the payload size.
While you might expect that the effect of the optimization above would be minimal, we’ve seen significant performance discrepancies when the number of distinct log tags > 30. In other words, what could all fit into one request get split into >30 requests. This substantially increases latency and consumes significantly more resource usage.
On …

Disable split_logs_by_tag by default and fix a corner case when no valid entry is present.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

This way the googleauth lib knows to fetch the credentials following the fallback path.

Unset the credential file path environment variable if the value is an empty string.

---

.rubocop_todo.yml
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Today nested JSON detection only happens when the record has one field named "log", "message", "msg". The size of the hash matters.
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/8d26465c0f777a42938e3acae857936627a38511/lib/fluent/plugin/out_google_cloud.rb#L588
Fields like `logging.googleapis.com/trace`, `logging.googleapis.com/spanId` and `logging.googleapis.com/insertId` should not count towards the hash size when determining whether to extract JSON from the nested field.

Fix cascading JSON detection with LogEntry fields.

---

Rakefile
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

When metadata concealment is enabled, kube-env is not available to pods outside of `hostNetwork`.

Use cluster-name directly instead of kube-env to populate cluster_name label

---

lib/fluent/plugin/filter_add_insert_ids.rb
test/plugin/test_filter_add_insert_ids.rb

Change `Fluent::Plugin::AddInsertIdsFilter` to `Fluent::AddInsertIdsFilter`.
Option 1:
Merge in this PR.
Option 2:
Abandon this PR. Instead revert the new add_insert_ids plugin, do a release without it. Upgrade to Fluentd v1.2 then and release add_insert_ids plugin in the next release.
Option 3:
Abandon this PR. Instead Merge the Fluentd v1.2 upgrade (https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/240) now that includes marking Fluentd v1.2 as a dependency.

Use Fluentd v0.12 compatible module path.

---

fluent-plugin-google-cloud.gemspec

Upgrade Fluentd to v1.2.5 (latest as of Aug 24, 2018) to apply this fix https://github.com/fluent/fluentd/issues/1941.
Fixes #251.

Upgrade Fluentd to v1.2.5 and bump gem version to v0.7.0.

---

lib/fluent/plugin/out_google_cloud.rb

Turned out the original implementation caused memory usage regression.

Use file path regex to determine current gem version.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/constants.rb

Currently server IP is not extracted correctly, resulting in log entry like below:
```
{
httpRequest: {
requestMethod:  "GET"   
requestSize:  "777"   
requestUrl:  "/"   
status:  200   
userAgent:  "Opera/12.0"   
}
jsonPayload: {
httpRequest: {
serverIp:  "192.168.0.1"    
}
...
}
...
}
```

Add field extraction for httpRequest.serverIp.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb

Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/271

 Add cache_fill_bytes, cache_lookup and protocol field extraction from httpRequest.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

Extract `logging.googleapis.com/labels` (the field name can be customized by the configuration `labels_key`) and set those labels in logEntry->labels.
If a `logging.googleapis.com/labels` field (or a customized field whose name is specified by `labels_key`) is present in the log entry, the field is stripped from the payload and assigned to the [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) labels field.
This is similar to how we handle the other fields for logEntry: https://cloud.google.com/logging/docs/agent/configuration#special-fields
Example:
Original log entry
```
{ 
"message":  "this is a test message",
"code": "user",
"logging.googleapis.com/labels": {
"app":  "logging-load-test",     
"node":  "default-pool-3edf6d28-v1np",     
"pod-template-hash": …
```

 Add logEntry->labels auto extraction.

---

fluent-plugin-google-cloud.gemspec

grpc has fixed certain bugs, and include https_proxy environment variable features we might be interested:
- [memory leak in ruby when exception is raised in 1.10.0](https://github.com/grpc/grpc/pull/14132)
- memory leak in core module's max_age_filter and http_proxy in 1.10.0.
- [grpc core module fixes memory leak on flow control in 1.10.1](https://github.com/grpc/grpc/pull/14747)
- [https_proxy environment variable can be set in grpc core in 1.14.0](https://github.com/grpc/grpc/pull/15698)
Do not bump further because this is the minimum version provided the above bug fixes and features.

Bump grpc version to 1.14.2.

---

lib/fluent/plugin/out_google_cloud.rb

This enables launching two or more fluentd workers to utilize multiple CPU cores.

Mark the plugin multi_workers_ready.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

[Warnings]
2019-03-11 20:49:54 +0000 [warn]: #0 [google_cloud] got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each_codepoint' for #<Hash:0x00007f1bac785ce8>\nDid you mean?  each_cons
2019-03-11 20:49:54 +0000 [warn]: #0 [google_cloud] bad chunk is moved to /var/log/fluentd/backup/worker0/google_cloud/583d7977dc71f7fcd9a7f697a08b4483.log
[Code Snippet where the warn is thrown]
```
def parse_json_or_nil(input)
return nil if input.nil?
input.each_codepoint do |c|
if c == 123
begin
return JSON.parse(input)
rescue JSON::ParserError
return nil
end
else
break unless c == 9 || c == 10 || c == 13 || c == 32
end # case
end # do
nil
end
```

Fix each_codepoint undefined error when input is not a string.

---

lib/fluent/plugin/out_google_cloud.rb

We are seeing misleading logs when starting logging agent in debug mode in GKE On-prem:
2019-06-23 01:41:07 +0000 [debug]: #1 [google_cloud] Failed to retrieve monitored resource from Metadata Agent with local_resource_id k8s_container.kube-system.calico-typha-b787b5b99-t8kr9.calico-typha.
This log should only be present when @enable_metadata_agent is true.

Mute "Failed to retrieve monitored resource from Metadata Agent" logs when @enable_metadata_agent is false.

---

lib/fluent/plugin/out_google_cloud.rb

We are seeing misleading errors when logging agent starts up:
[Error]
```
2019-06-23 00:53:53 +0000 [info]: [google_cloud] use_metadata_service is false; not detecting platform
2019-06-23 00:53:53 +0000 [error]: [google_cloud] Failed to set monitored resource labels for gce_instance:  error_class=RuntimeError error="Cannot construct a gce_instance resource without vm_id and zone"
```

Mute 'Failed to set monitored resource labels for gce_instance' error for GKE On-Prem.

---

lib/fluent/plugin/out_google_cloud.rb

This message is not harmful, just a bit misleading when debugging other issues.
```
/opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.7.13/lib/fluent/plugin/out_google_cloud.rb:47: warning: already initialized constant Google::Auth::CredentialsLoader::GCLOUD_CONFIG_COMMAND
/opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/googleauth-0.8.1/lib/googleauth/credentials_loader.rb:52: warning: previous definition of GCLOUD_CONFIG_COMMAND was here
```

Mute "warning: already initialized constant" message in the log.

---

lib/fluent/plugin/out_google_cloud.rb

This is a follow-on to #310 (and #319).

Completely disable gcloud credential lookups rather than silence them.

---

lib/fluent/plugin/out_google_cloud.rb

We know the metadata server is local, so we don't need a proxy. Today, if a user sets up a proxy with the intention of using it for connections to the Logging service, they'll break the metadata requests.
Fixes #101

Skip proxy for local metadata requests

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

This includes the fix for https://github.com/protocolbuffers/protobuf/pull/5752 and 
https://github.com/googleapis/google-cloud-ruby/issues/2876.
google-protobuf 3.7.0 introduced a bunch of JSON serialization/deserialization changes: https://github.com/googleapis/google-cloud-ruby/issues/2900. That broke a ton of our unit tests (https://travis-ci.org/GoogleCloudPlatform/fluent-plugin-google-cloud/jobs/563866931 comes with 15 failures, 41 errors).

Update google-protobuf gem to 3.9.0 and adjust unit tests accordingly.

---

fluent-plugin-google-cloud.gemspec

* Upgrade Fluentd to 1.6.3.
* Upgrade google-api-client to 0.30.8.
* Upgrade google-cloud-logging to 1.6.6.
* Upgrade googleapis-common-protos to 1.3.9.
* Upgrade googleauth to 0.9.0.
* Upgrade json to 2.2.0.

Upgrade dependency versions.

---

lib/fluent/plugin/in_object_space_dump.rb

It uses the objspace module documented here: http://tmm1.net/ruby21-objspace/
Here are more examples on how to use this data: https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby
@StevenYCChou the PRNG chose you as the reviewer.
@qingling128 please review for Ruby readability and general "does this go in this package".

Introduced new plugin for memory profiling

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

The client library had a breaking change to its API. I decided to fix this as pre-work for making the monitoring code also support OpenCensus, so we can use the new API as the common API for the abstraction on top of both.

Upgraded to Prometheus client 0.10.0.

---

test/plugin/test_driver.rb

This brings down text execution from >5 minutes to <20 seconds. The tests all pass, hopefully they don't become flaky. Upstream is unclear about why the waits were needed, I'll follow up with them: https://github.com/fluent/fluentd/blob/master/lib/fluent/test/base.rb#L64-L75
Upstream discussion (just posted): https://groups.google.com/d/topic/fluentd/ze7YY1ue40s/discussion

Remove waits on test start-up.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

I didn't simply revert #342 because I want to preserve the changes in out_google_cloud for my my follow-up change to support OpenCensus. It will also be much easier to support prometheus client 0.10.0 on top of this change:
- Add the `labels:`, `docstring:`, and `by:` prefixes to the `counter.increment` and `registry.counter` calls in monitoring.rb.
- Add the `labels:` prefix to the assert_prometheus metric method in base_test.rb.

Backported to prometheus client 0.9.0

---

lib/fluent/plugin/monitoring.rb

The labels argument was in an unexpected format that none of our tests caught, and it's undocumented for the client library 0.9.0 that we use. Once we upgrade to 0.10.0, we should revert this change.

Fixed Prometheus counter instantiation

---

README.rdoc

While I have been using this plugin for a while, I've been always confused by the first paragraph of README:
Screenshot:
I suggest combining them into single lines and make it looks like screenshot below:

Update layout for README

---

lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

The format of version is `google-fluentd/1.2.3-foo`. It's quite inconvenient in Ruby to extract the Linux distro in a portable manner like we do in the collectd build system. @igorpeshansky in case you know that we already have this, but otherwise feel free to ignore.

Emit the uptime metric

---

lib/fluent/plugin/out_google_cloud.rb

This reduces CPU usage in micro and macro benchmarks of our GKE setup by 20-30%. I ran the macro benchmark with Ruby 2.6.3, and the micro benchmark with Ruby 2.5.7 and 2.6.3.
Thanks to @igorpeshansky for the tip on how to monkey patch the method.
```ruby
require 'time'
1000000.times { Time.strptime("1227 20:39:23.1234 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
, "%m%d %H:%M:%S.%N") }                                                                                                                               
require 'strptime'
strptime = Strptime.new("%m%d %H:%M:%S.%N")
1000000.times { strptime.exec("1227 20:39:23.1234 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
) } …
```

Use Ruby's builtin time parser.

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

Fix a bug in timestamp adjustment (we should accept timestamps that are up to one day in the future, regardless of the date).
Fix broken tests that were computing the wrong expected values on December 31.

Handle an edge case for timestamp adjustment (December 31).

---

lib/fluent/plugin/out_google_cloud.rb

It only works with gRPC channels, which is the default. This needs to be enabled via configuration, because there is a CPU cost.

Add a config param grpc_compression_algorithm to support payload compression for gRPC path.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb

This allows us to override the address to use a non-production endpoint.
Tested: Built gem, installed on VM, updated google-fluentd.conf to
override gcm_service_address, restarted google-fluentd, observed no
errors in logs.

Add config param for Google Cloud Monitoring service address.

---

fluent-plugin-google-cloud.gemspec

Minor version bump due to:
- #371 : partial_success flag deprecated
- #375 : docker monitored resources deprecated
- #376 : metadata agent support deprecated

Bump version to 0.8.0

---

fluent-plugin-google-cloud.gemspec

Fixes the following error:
```
Unable to export to Monitoring service because: unknown keyword: service_address
```

Bump opencensus-stackdriver to fix a dependency issue.

---

lib/fluent/plugin/out_google_cloud.rb

From https://github.com/fluent/fluentd/issues/2871
Fluentd v1.7.4 has Fluent:: MessagePackFactory.engine_factory which is same as the . Fluent::Engine.msgpack_factory
https://github.com/fluent/fluentd/blob/v1.7.4/lib/fluent/msgpack_factory.rb#L38

Replace deprecated Engine.msgpack_factory method with new MessagePackFactory.engine_factory method.

---

lib/fluent/plugin/out_google_cloud.rb

This fixes the newly enforced git-secrets integration warning:
```
[ERROR] Matched one or more prohibited patterns
Possible mitigations:
- Mark false positives as allowed using: git config --add secrets.allowed ...
- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory
- List your configured patterns: git config --get-all secrets.patterns
- List your configured allowed patterns: git config --get-all secrets.allowed
- List your configured allowed patterns in .gitallowed at repository's root directory
- Use --no-verify if this is a one-time false positive
F0805 16:41:47.656311   77047 google_hook.go:84] git-secrets failed with error: exit status 1
```

Remove fake sensitive user data in comments to get rid of warnings.

---

lib/fluent/plugin/out_google_cloud.rb

This enables writing metrics against that resource as well.
The Logging API would accept either `container` or `gke_container` as aliases.

Switch to using the gke_container for legacy GKE resources.

---

test/plugin/test_driver.rb

Reverts #343 to restore test waits to avoid broken tests being shown as passed.

Revert "Remove waits on test start-up. (#343)".

---

lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb

Document the 'opencensus' monitoring_type value.

---

lib/fluent/plugin/common.rb
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/constants.rb

This controls the monitored resource for reporting OpenCensus metrics.

Add a metrics_resource configuration option.

---

fluent-plugin-google-cloud.gemspec

Bumping minor version due to [new functionality for configuring metrics](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/410).

Bump gem version to 0.9.0 for future releases.

---

fluent-plugin-google-cloud.gemspec

gRPC 1.30.1 and ruby 2.5.5/2.6.5/2.7.0 has such error:
``C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': Couldn't find or load gRPC's dynamic C core (LoadError)``
gRPC 1.30.2 picks up a fix for windows linkage missing.  See comment here: https://github.com/grpc/grpc/issues/23423#issuecomment-663725014

Upgrade gRPC to 1.30.2

---

fluent-plugin-google-cloud.gemspec

Tested the current logging agent release against a new agent which includes the changes in this PR, plus the same fluentd update in google-fluentd (https://github.com/GoogleCloudPlatform/google-fluentd/pull/283). Metrics look good:
CPU
RSS
Throughput

Upgrade fluentd to v1.11.2 (from v1.7.4).

---

fluent-plugin-google-cloud.gemspec

Picks up https://github.com/grpc/grpc/pull/23333 that was released in the 1.31.1 gem yesterday.

Update grpc gem dependency version to 1.31.1.

---

lib/fluent/plugin/filter_analyze_config.rb
test/plugin/test_filter_analyze_config.rb

* Rename the label name from "has_default_value" to "has_default_config".
* Rename the metrics name from "config_usage" to "plugin_config".
* Change the metrics description from "Parameter usage for Google Cloud
plugins" to "Configuration parameter usage for plugins relevant to Google
Cloud."

Minor renaming of metrics name and label names.

---

lib/fluent/plugin/filter_analyze_config.rb

Fixes a few dependency errors like this one:
```
2020-09-16 05:40:40 +0000 [warn]: analyze_config plugin: Failed to optionally analyze the google-fluentd configuration file. Proceeding anyway. Error: uninitialized constant Common::Utils::CredentialsInfo::Google. Trace: ["/opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.10.3/lib/fluent/plugin/common.rb:354:in `project_id'", "/opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.10.3/lib/fluent/plugin/common.rb:175:in `get_project_id'", "/opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.10.3/lib/fluent/plugin/filter_analyze_config.rb:220:in `configure'", "/opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin.rb:173 …
```

Fix analyze_config plugin imports.

---

lib/fluent/plugin/filter_analyze_config.rb
lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb
test/plugin/base_test.rb
test/plugin/test_filter_analyze_config.rb

Per discussion offline, we want to send the metrics under `internal/logging/config` instead.
Tested via local Prometheus endpoint in b/153356846. Also tested metrics prefix customization by changing the default prefix temporarily and verify the ingestion of `request_count` metrics.

Make metrics prefix parameterized in the opencensus path.

---

lib/fluent/plugin/filter_analyze_config.rb
lib/fluent/plugin/monitoring.rb

Sample debugging log:
```
2020-11-10 16:31:26 +0000 [info]: #0 analyze_config plugin: Starting to configure the plugin.
2020-11-10 16:31:26 +0000 [info]: #0 analyze_config plugin: google-fluentd configuration file found at /etc/google-fluentd/google-fluentd.conf. google-fluentd baseline configuration file found at /etc/google-fluentd/baseline/google-fluentd.conf. google-fluentd Analyzing configuration.
2020-11-10 16:31:26 +0000 [info]: #0 monitoring module: Successfully initialized Open Census monitoring registry.
2020-11-10 16:31:26 +0000 [info]: #0 analyze_config plugin: Registering counters.
2020-11-10 16:31:27 +0000 [info]: #0 monitoring module: Registered recorders and exporters for agent.googleapis.com/agent/internal/logging/config.
2020-11-10 16:31:27 +0000 [info]: #0 monitoring …
```

Add debugging logs for the analyze_config plugin.

---

lib/fluent/plugin/filter_analyze_config.rb
lib/fluent/plugin/monitoring.rb
lib/fluent/plugin/out_google_cloud.rb
test/plugin/asserts.rb
test/plugin/base_test.rb
test/plugin/test_filter_analyze_config.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb

* Add the accidentally removed resource_type back.
* Send the config analysis metrics as GAUGE instead of CUMULATIVE.
* Schedule the config analysis metrics to be exported.

Fix monitoring metrics ingestion via open census.

---

fluent-plugin-google-cloud.gemspec

These versions allow this plugin to coexist with other Google Cloud gems, such as google-cloud-pubsub. This enables the following `Gemfile` to work:
```ruby
source 'https://rubygems.org'
gem 'fluent-plugin-google-cloud', '0.10.7'
gem 'google-cloud-pubsub', '2.3.1'
```

Relax some Gem dependencies

---

fluent-plugin-google-cloud.gemspec

- increment gem version for plugin
- update to allow fluentd v1.12.3 gem
- update json to 2.4.1 for [CVE-2020-10663](https://www.ruby-lang.org/en/news/2020/03/19/json-dos-cve-2020-10663/)
Signed-off-by: Anton Ouzounov <aouzounov@vmware.com>
Hello maintainers! We are using fluentd-plugin-google-cloud as a plugin in the [kube-fluentd-operator](https://github.com/vmware/kube-fluentd-operator) . We want to be able to migrate to using fluentd v1.12.0 for the benefit of our users, this is the only plugin currently forcing us to use fluentd v1.11.2 . Can we help upgrade? I don't see any breaking changes in the [fluentd changelogs](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md) that will present problems.

chore: update to fluentd v1.12.3

---

fluent-plugin-google-cloud.gemspec

Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/447#issuecomment-847187748

Revert Fluentd from 1.12.3 to 1.11.2 for memory / cpu regression.

---

lib/fluent/plugin/filter_analyze_config.rb
lib/fluent/plugin/monitoring.rb

http://b/202988791
Updates timestamps for all config analysis metrics before exporting them, without changing any of the measurement tags or values. It creates a "new" data point for each existing time series, by reusing its old value and manually updating the associated time. This is a special case, since we want these to be constant-value gauge metrics, and we don't want to re-parse the user's config every minute.
Before, the exact same config analysis metrics were being sent every minute (same time series, same values, same times), so metrics were only ever ingested for the first export after start-up, and after 24h, it would result in Monitoring API errors and audit logs every minute that looked like:
> Field timeSeries[0].points[0].interval.end_time had an invalid value of …

Update constant gauge timestamps before exporting.

---

fluent-plugin-google-cloud.gemspec

http://b/202988791
This picks up the fix for creating gauge points (https://github.com/census-ecosystem/opencensus-ruby-exporter-stackdriver/pull/28), that (together with https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/477) will enable our config usage metrics to be correctly exported every minute.
When the next Logging Agent is released with this, https://github.com/GoogleCloudPlatform/google-fluentd/issues/345 will be fixed.

Update opencensus-stackdriver to 0.4.1.

---

.github/workflows/ci.yml

http://b/219963999
Upgrading grpc from `1.31.1` → `1.43.1` requires Ruby >= `2.5.0`

Remove Ruby 2.4 and add 2.7 in the testing grid.

---

fluent-plugin-google-cloud.gemspec

Due to a bug in grpc gem you cannot compile this plugin after 10.0 on ARM architecture https://github.com/grpc/grpc/issues/23889
We need to bump this dep up to support native arm extensions

chore: bump grpc gem to 1.43.1

---

fluent-plugin-google-cloud.gemspec

This is to allow building the logging agent with Ruby 3 later, avoiding errors like this (caused by https://github.com/rubygems/rubygems/issues/4338):
```
ERROR:  While executing gem ... (NoMethodError)
undefined method `request' for nil:NilClass
[@failed_dep.dependency, @activated.request.dependency]
^^^^^^^^
/[usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/resolver/conflict.rb:47](https://cs.corp.google.com/piper///depot/google3/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/resolver/conflict.rb?l=47&cl=514852906):in `conflicting_dependencies'
/[usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/exceptions.rb:61](https://cs.corp.google.com/piper///depot/google3/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/exceptions.rb?l=61&cl=514852906):in …
```

Bump google-api-client to be compatible with Ruby 3.

---

fluent-plugin-google-cloud.gemspec
lib/fluent/plugin/filter_add_insert_ids.rb
lib/fluent/plugin/out_google_cloud.rb
lib/fluent/plugin/statusz.rb
test/plugin/base_test.rb
test/plugin/constants.rb
test/plugin/test_out_google_cloud.rb
test/plugin/test_out_google_cloud_grpc.rb
test/plugin/utils.rb

[b/254273286](http://b/254273286).

Update fluent-plugin-google-cloud to work with Ruby 3.

---

fluent-plugin-google-cloud.gemspec

Tracker: (b/293350172](b/293350172)
There have been several memory leak fixes since v1.13.3. Updating the version and having this run using our soak tests will help us see if we see some improvements. 
Related PR: https://github.com/GoogleCloudPlatform/google-fluentd/pull/422

gemspec: update fluentd version to v1.16.2

---

.github/workflows/ci.yml
.rubocop.yml
fluent-plugin-google-cloud.gemspec

Need a newer version of gRPC for compatibility with Ruby 3.3.5.
gRPC requires Ruby 3.x starting with version 1.66.0, so pick the newest version before 1.66.0.
That version requires Ruby 2.7, so upgrade to that as well.

Upgrade gRPC to 1.65.2, Ruby to 2.7

---

fluent-plugin-google-cloud.gemspec

CVE-2023-28120, CVE-2023-22796, CVE-2023-38037: `activesupport` is a transitive dependency of `google-api-client`, which has not been updated upstream to a patched version, so we are pinning it here instead.

Pin activesupport version
